name: Build llava base

on:
  push:
    branches: ["runpod"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - name: Set up Docker Buildx
      #  uses: docker/setup-buildx-action@v3

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: true

          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: false

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password:
            ${{ secrets.DOCKERHUB_TOKEN }}

            # Build the Docker image first
      - uses: docker/build-push-action@v4
        with:
          push: false
          file: base.Dockerfile
          tags: bferns/kwave-llava-runpod-base:temp

      # Slim it!
      - uses: kitabisa/docker-slim-action@v1
        id: slim
        env:
          DSLIM_HTTP_PROBE: false
        with:
          target: bferns/kwave-llava-runpod:temp
          tag: ${{  github.ref_name }}

      # Dump the report
      - run: echo "${REPORT}"
        env:
          REPORT: ${{ steps.slim.outputs.report }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: bferns/kwave-llava-runpod:${{  github.ref_name }}
